version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - leetcode-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pwhateveryouwant"]
      interval: 10s
      timeout: 5s
      retries: 5

  dashboard-service:
    build:
      context: .
      dockerfile: dashboard-service/Dockerfile
    container_name: dashboard-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/leetcodedashboard?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN:-http://localhost:*}
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - leetcode-network

  ai-service:
    build:
      context: .
      dockerfile: ai-service/Dockerfile
    container_name: ai-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/aiservicedashboard?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - OPEN_AI_API_KEY=${OPEN_AI_API_KEY}
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - leetcode-network

  battle-service:
    build:
      context: .
      dockerfile: battle-service/Dockerfile
    container_name: battle-service
    user: root  # Gives permission to interact with docker.sock
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/leetcodedashboardBattle?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - AI_SERVICE_BASE_URL=http://ai-service:8085
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN:-http://localhost:*}
      - SPRING_DATA_REDIS_HOST=redis-16937.c90.us-east-1-3.ec2.cloud.redislabs.com
      - SPRING_DATA_REDIS_PORT=16937
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD}
      - HOST_SUBMISSIONS_PATH=/home/ubuntu/battle-submissions
    volumes:
      # Mount EC2 host Docker socket so battle-service can spawn containers
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/battle-submissions:/battle-submissions
    depends_on:
      mysql-db:
        condition: service_healthy
      ai-service:
        condition: service_started
    networks:
      - leetcode-network

volumes:
  mysql_data:

networks:
  leetcode-network:
    driver: bridge
