spring.application.name=ai-service
server.port=8085
spring.ai.openai.chat.options.model=gpt-5-mini
spring.ai.openai.api-key=${SPRING_AI_OPENAI_API_KEY:${OPEN_AI_API_KEY:}}
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
spring.datasource.url=jdbc:mysql://localhost:3306/aiservicedashboard?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.ai=DEBUG
platform.problems.max-generation-limit=5
